In [5]:
%load_ext autoreload
%autoreload 2

from extract_raw_data import extract_data
from json_to_seq2seq import to_seq2seq

# !pip install pandas
# !pip install nltk
# !pip install sklearn
# extract_data()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Requirement already satisfied: pandas in /usr/local/lib/python3.5/dist-packages (0.24.2)
Requirement already satisfied: pytz>=2011k in /usr/local/lib/python3.5/dist-packages (from pandas) (2019.1)
Requirement already satisfied: python-dateutil>=2.5.0 in /usr/local/lib/python3.5/dist-packages (from pandas) (2.8.0)
Requirement already satisfied: numpy>=1.12.0 in /usr/local/lib/python3.5/dist-packages (from pandas) (1.16.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.5/dist-packages (from python-dateutil>=2.5.0->pandas) (1.12.0)
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied: nltk in /usr/local/lib/python3.5/dist-packages (3.4.1)
Requirement already satisfied: six in /usr/local/lib/python3.5/dist-packages (from nltk) (1.12.0)
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting sklearn
  Downloading https://files.pythonhosted.org/packages/1e/7a/dbb3be0ce9bd5c8b7e3d87328e79063f8b263b2b1bfa4774cb1147bfcd3f/sklearn-0.0.tar.gz
Collecting scikit-learn (from sklearn)
  Downloading https://files.pythonhosted.org/packages/38/7f/7d21bd89a97603a14d3770ca912d4402c394a8e50642f9b8b5cc6867a61a/scikit_learn-0.20.3-cp35-cp35m-manylinux1_x86_64.whl (5.3MB)
    100% |████████████████████████████████| 5.3MB 7.5MB/s eta 0:00:01
Requirement already satisfied: numpy>=1.8.2 in /usr/local/lib/python3.5/dist-packages (from scikit-learn->sklearn) (1.16.2)
Collecting scipy>=0.13.3 (from scikit-learn->sklearn)
  Downloading https://files.pythonhosted.org/packages/f0/30/526bee2ce18c066f9ff13ba89603f6c2b96c9fd406b57a21a7ba14bf5679/scipy-1.2.1-cp35-cp35m-manylinux1_x86_64.whl (24.7MB)
    100% |████████████████████████████████| 24.7MB 1.9MB/s eta 0:00:01   18% |██████                          | 4.6MB 82.0MB/s eta 0:00:01    61% |███████████████████▋            | 15.1MB 79.4MB/s eta 0:00:01
Building wheels for collected packages: sklearn
  Building wheel for sklearn (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/76/03/bb/589d421d27431bcd2c6da284d5f2286c8e3b2ea3cf1594c074
Successfully built sklearn
Installing collected packages: scipy, scikit-learn, sklearn
Successfully installed scikit-learn-0.20.3 scipy-1.2.1 sklearn-0.0
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [12]:
import pandas as pd

df = pd.read_json("/tf/datagen/conala-train.json")
df.head()

,intent,question_id,rewritten_intent,snippet
0,How to convert a list of multiple integers int...,41067960,Concatenate elements of a list 'x' of multiple...,"sum(d * 10 ** i for i, d in enumerate(x[::-1]))"
1,How to convert a list of multiple integers int...,41067960,convert a list of integers into a single integer,"r = int(''.join(map(str, x)))"
2,how to convert a datetime string back to datet...,4170655,convert a DateTime string back to a DateTime o...,datetime.strptime('2010-11-13 10:33:54.227806'...
3,Averaging the values in a dictionary based on ...,29565452,get the average of a list values for each key ...,"[(i, sum(j) / len(j)) for i, j in list(d.items..."
4,zip lists in python,13704860,"zip two lists `[1, 2]` and `[3, 4]` into a lis...","zip([1, 2], [3, 4])"

In [16]:
from pathlib import Path
contents = Path("/tf/datagen/conala-mined.jsonl").read_text()
contents = contents.splitlines()
df2 = pd.DataFrame([dict(eval(x)) for x in contents])
df2.head()

,id,intent,parent_answer_post_id,prob,question_id,snippet
0,34705205_34705233_0,Sort a nested list by two elements,34705233,0.869000,34705205,"sorted(l, key=lambda x: (-int(x[1]), x[0]))"
1,13905936_13905946_0,converting integer to list in python,13905946,0.852670,13905936,[int(x) for x in str(num)]
2,13837848_13838041_0,Converting byte string in unicode string,13838041,0.852143,13837848,c.decode('unicode_escape')
3,23490152_23490179_0,List of arguments with argparse,23490179,0.850829,23490152,"parser.add_argument('-t', dest='table', help='..."
4,2721782_2721807_0,How to convert a Date string to a DateTime obj...,2721807,0.840372,2721782,"datetime.datetime.strptime(s, '%Y-%m-%dT%H:%M:..."

In [25]:
df3 = pd.DataFrame([])
df3 = df3.append(df)
df3 = df3.append(df2)
df3.shape

/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

(596270, 7)

In [19]:
df3.head()

,intent,question_id,rewritten_intent,snippet,id,parent_answer_post_id,prob
0,How to convert a list of multiple integers int...,41067960,Concatenate elements of a list 'x' of multiple...,"sum(d * 10 ** i for i, d in enumerate(x[::-1]))",NaN,NaN,NaN
1,How to convert a list of multiple integers int...,41067960,convert a list of integers into a single integer,"r = int(''.join(map(str, x)))",NaN,NaN,NaN
2,how to convert a datetime string back to datet...,4170655,convert a DateTime string back to a DateTime o...,datetime.strptime('2010-11-13 10:33:54.227806'...,NaN,NaN,NaN
3,Averaging the values in a dictionary based on ...,29565452,get the average of a list values for each key ...,"[(i, sum(j) / len(j)) for i, j in list(d.items...",NaN,NaN,NaN
4,zip lists in python,13704860,"zip two lists `[1, 2]` and `[3, 4]` into a lis...","zip([1, 2], [3, 4])",NaN,NaN,NaN